### ISSUE TITLE
Can add items to bill

### ISSUE THREAD

**Issue by oynp** [oy-np/billshare#1]
As Oy, I want to create an item with item name, unit price, unit and total price so I can start creating items for main bill. 

**Tasks**
- Each item should have `total_price, unit_price and units`

**Exit Criteria**
- [ ] Can add new item with `item name, unit price, unit and total price` to main bill
- [ ] Can list item with `item name, unit price, unit and total price`
- [ ] Can edit or delete item
